services:
  be-uml:
    build: .
    container_name: uml_be
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: postgres-db
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:15-alpine
    container_name: uml_postgres

    restart: always

    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "${DB_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: uml_pgadmin

    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

    ports:
      - "${PGADMIN_PORT}:80"

    depends_on:
      - postgres-db

  qdrant:
    image: qdrant/qdrant:latest
    container_name: uml_qdrant
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  anythingllm:
    image: mintplexlabs/anythingllm:latest
    container_name: uml_anythingllm
    restart: always
    ports:
      - "3001:3001"
    cap_add:
      - SYS_ADMIN
    environment:
      - STORAGE_DIR=/app/server/storage
    volumes:
      - anythingllm_data:/app/server/storage

volumes:
  postgres_data:
  qdrant_data:
  anythingllm_data: